name: Build VitePress, Pull Types, and Push to Private Repo

on:
    push:
        branches: [main]

jobs:
    setup-build-and-push:
        runs-on: self-hosted
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Pull types from type repo
              run: |
                  if ! grep -q github.com ~/.ssh/known_hosts; then
                      ssh-keyscan github.com >> ~/.ssh/known_hosts
                  fi
                  GIT_SSH_COMMAND='ssh -i /home/mihono/.ssh/id_rsa' git clone --depth 1 git@github.com:M1hono/CrychicDocTypes.git type_repo
                  cp -r type_repo/typefiles .
                  rm -rf type_repo
                  echo "Types pulled successfully"

            - name: Configure Yarn to use a faster registry
              run: yarn config set registry https://registry.npmmirror.com

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20.17.0"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build VitePress site
              env:
                NODE_OPTIONS: --max-old-space-size=8192
              run: |
                  echo "Building VitePress site..."
                  yarn docs:build
                  echo "VitePress site build completed"

            # 在合并后的任务中，直接处理推送
            - name: Setup Git
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"

            - name: Clone workflow file
              run: |
                  # 改进版本
                  if ! grep -q github.com ~/.ssh/known_hosts; then
                      ssh-keyscan github.com >> ~/.ssh/known_hosts || exit 1
                  fi

                  mkdir -p temp_repo || exit 1
                  cd temp_repo || exit 1
                  git init || exit 1
                  git remote add -f origin git@github.com:M1hono/CrychicDocSynchronization.git || exit 1
                  git config core.sparseCheckout true || exit 1
                  echo ".github/workflows/deploy.yaml" >> .git/info/sparse-checkout
                  mkdir -p ../.vitepress/dist/.github/workflows/ || exit 1
                  GIT_SSH_COMMAND='ssh -i /home/mihono/.ssh/id_rsa' git pull origin main --depth 1 || exit 1

                  if [ -f .github/workflows/deploy.yaml ]; then
                      cp .github/workflows/deploy.yaml ../.vitepress/dist/.github/workflows/ || exit 1
                      echo "指定文件拉取并复制成功"
                  else
                      echo "错误：未找到目标文件"
                      exit 1
                  fi

            - name: Push to private repo
              run: |
                  cd .vitepress/dist
                  git init
                  git add -A
                  git commit -m "Update documentation"
                  GIT_SSH_COMMAND='ssh -i /home/mihono/.ssh/id_rsa' git push --force git@github.com:M1hono/CrychicDocSynchronization.git HEAD:main
                  echo "Push completed"

            - name: Cleanup
              run: |
                  rm -rf typefiles
                  rm -rf .vitepress/dist
                  rm -rf temp_repo
                  echo "Cleanup completed"
